version: "3"
networks:
  my-network:
    driver: bridge
 
services:
 
  db: 
    image: mariadb
    networks:
      - my-network
    container_name: mariadb
    environment: 
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: libreria
      MARIADB_PASSWORD: root
    ports:
      - 3306:3306
 
  backend:
    build: .
    networks:
      - my-network
    container_name: backend
    ports:
      - 8080:8080
    depends_on: 
      - db
 
  frontend:
    image: frontend4.10
    container_name: frontend
    ports:
      - 4200:4200
    networks:
      - my-network